FROM golang:1.23 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o worker ./cmd/consumer/worker.go

FROM golang:1.23

WORKDIR /root/

COPY --from=builder /app/worker .

CMD ["/root/worker"]
