version: "3.9"

services:
  cpf-cnpj-api:
    build: .
    container_name: cpf-cnpj-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - cpf-cnpj-db
    networks:
      - app-network
  cpf-cnpj-db:
    image: postgres:15
    container_name: cpf-cnpj-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cpf_cnpj_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
