version: "3.9"

services:
  cpf-cnpj-api:
    build: .
    container_name: cpf-cnpj-api
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - cpf-cnpj-db
      - rabbitmq
    networks:
      - app-network

  cpf-cnpj-db:
    image: postgres:15
    container_name: cpf-cnpj-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cpf_cnpj_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - cpf-cnpj-api
      - rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
